#!/usr/bin/env bash
# =============================================================================
# ETMS — one-command first deploy on a fresh Ubuntu/Debian server.
#
#   curl -fsSL https://raw.githubusercontent.com/wessamsamir1-stack/etms/main/deploy/bootstrap.sh \
#     | sudo bash -s -- --domain api.example.com --email you@example.com
#
# or, from a clone:  sudo ./deploy/bootstrap.sh --domain api.example.com
#
# It installs Docker if missing, generates every secret once into
# deploy/.env.prod (and never regenerates them on a re-run), points nginx at
# your domain, brings the stack up, and — with --email — issues a Let's Encrypt
# certificate. Safe to re-run: it is the upgrade path too.
#
# Without --domain the stack still comes up on plain HTTP for a smoke test, but
# the Android app will refuse a cleartext API, so a domain + TLS is what you
# actually want.
# =============================================================================
set -euo pipefail

REPO_URL="${ETMS_REPO_URL:-https://github.com/wessamsamir1-stack/etms.git}"
BRANCH="${ETMS_BRANCH:-main}"
INSTALL_DIR="${ETMS_DIR:-/opt/etms}"
DOMAIN=""
EMAIL=""

while [ $# -gt 0 ]; do
  case "$1" in
    --domain) DOMAIN="${2:?--domain needs a hostname}"; shift 2 ;;
    --email)  EMAIL="${2:?--email needs an address}";   shift 2 ;;
    --branch) BRANCH="${2:?--branch needs a name}";     shift 2 ;;
    --dir)    INSTALL_DIR="${2:?--dir needs a path}";   shift 2 ;;
    -h|--help) sed -n '2,20p' "$0"; exit 0 ;;
    *) echo "unknown option: $1" >&2; exit 2 ;;
  esac
done

say() { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die() { printf '\n\033[1;31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run me as root (sudo)."
command -v openssl >/dev/null || die "openssl is required."

# ---- Docker ----------------------------------------------------------------
if ! command -v docker >/dev/null; then
  say "Installing Docker"
  curl -fsSL https://get.docker.com | sh
fi
docker compose version >/dev/null 2>&1 || die "the Docker Compose plugin is missing."

# ---- Source ----------------------------------------------------------------
if [ -d "$INSTALL_DIR/.git" ]; then
  say "Updating $INSTALL_DIR ($BRANCH)"
  git -C "$INSTALL_DIR" fetch --depth 1 origin "$BRANCH"
  git -C "$INSTALL_DIR" checkout -B "$BRANCH" "origin/$BRANCH"
else
  say "Cloning into $INSTALL_DIR ($BRANCH)"
  git clone --depth 1 -b "$BRANCH" "$REPO_URL" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

ENV_FILE="deploy/.env.prod"
COMPOSE=(docker compose -f deploy/docker-compose.prod.yml --env-file "$ENV_FILE")

# ---- Secrets (generated once, never rotated by a re-run) -------------------
if [ -f "$ENV_FILE" ]; then
  say "Keeping the existing $ENV_FILE"
else
  say "Generating secrets into $ENV_FILE"
  gen() { openssl rand -base64 36 | tr -d '/+=' | cut -c1-40; }
  ADMIN_PASSWORD="$(gen)"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy/bootstrap.sh on $(date -u +%FT%TZ). Keep this file secret.
POSTGRES_USER=etms_admin
POSTGRES_PASSWORD=$(gen)
POSTGRES_DB=etms

APP_DB_USER=etms_app_login
APP_DB_PASSWORD=$(gen)

PLATFORM_DB_USER=etms_platform_login
PLATFORM_DB_PASSWORD=$(gen)
PLATFORM_ADMIN_EMAIL=${EMAIL:-root@etms.local}
PLATFORM_ADMIN_PASSWORD=$ADMIN_PASSWORD

JWT_SECRET=$(gen)
QR_SECRET=$(gen)
FIELD_ENCRYPTION_KEYS=v1:$(openssl rand -base64 32)

CORS_ORIGIN=${DOMAIN:+https://$DOMAIN}

API_REPLICAS=2
PGBOUNCER_POOL_SIZE=25
PGBOUNCER_MAX_CLIENT_CONN=500
WORKER_INTERVAL_MS=2000
ETMS_TAG=latest
EOF
  # The API refuses to boot in production without an exact CORS origin; with no
  # domain yet, point it at the host so the stack still starts.
  if [ -z "$DOMAIN" ]; then
    sed -i "s|^CORS_ORIGIN=.*|CORS_ORIGIN=http://localhost|" "$ENV_FILE"
  fi
  chmod 600 "$ENV_FILE"
fi

# ---- nginx server_name -----------------------------------------------------
if [ -n "$DOMAIN" ]; then
  say "Pointing nginx at $DOMAIN"
  sed -i "s|^  server_name .*|  server_name $DOMAIN;|" deploy/nginx/conf.d/etms.conf
fi

# A self-signed placeholder so nginx can start before certbot has run; the real
# certificate replaces it below.
mkdir -p deploy/nginx/certs deploy/nginx/certbot deploy/nginx/letsencrypt
if [ ! -f deploy/nginx/certs/fullchain.pem ]; then
  say "Creating a temporary self-signed certificate"
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -keyout deploy/nginx/certs/privkey.pem \
    -out    deploy/nginx/certs/fullchain.pem \
    -subj "/CN=${DOMAIN:-etms.local}" >/dev/null 2>&1
fi

# ---- Up --------------------------------------------------------------------
say "Building and starting the stack (first run pulls images — a few minutes)"
"${COMPOSE[@]}" up -d --build

say "Waiting for the API to report ready"
for _ in $(seq 1 60); do
  if curl -fsS http://127.0.0.1/healthz >/dev/null 2>&1; then break; fi
  sleep 5
done

# ---- TLS -------------------------------------------------------------------
if [ -n "$DOMAIN" ] && [ -n "$EMAIL" ]; then
  say "Requesting a Let's Encrypt certificate for $DOMAIN"
  # The webroot is bind-mounted into nginx (see docker-compose.prod.yml), so the
  # ACME challenge certbot drops here is served straight away.
  if docker run --rm \
      -v "$PWD/deploy/nginx/letsencrypt:/etc/letsencrypt" \
      -v "$PWD/deploy/nginx/certbot:/var/www/certbot" \
      certbot/certbot certonly --webroot -w /var/www/certbot \
      -d "$DOMAIN" --email "$EMAIL" --agree-tos --non-interactive --cert-name etms
  then
    cp "deploy/nginx/letsencrypt/live/etms/fullchain.pem" deploy/nginx/certs/fullchain.pem
    cp "deploy/nginx/letsencrypt/live/etms/privkey.pem"   deploy/nginx/certs/privkey.pem
    "${COMPOSE[@]}" exec -T nginx nginx -s reload
    say "TLS is live. Renew with the same command from cron; certbot keeps its state in deploy/nginx/letsencrypt."
  else
    echo "certbot did not complete — the stack is up on the self-signed certificate."
    echo "Check that $DOMAIN resolves to this server and that port 80 is open, then re-run."
  fi
fi

# ---- Report ----------------------------------------------------------------
BASE="http://$(curl -fsS4 ifconfig.me 2>/dev/null || echo localhost)"
[ -n "$DOMAIN" ] && BASE="https://$DOMAIN"

say "Done"
cat <<EOF

  API           $BASE
  health        $BASE/health
  app API URL   $BASE/v1      <- set this as the ETMS_API_BASE_URL repo variable

  Platform admin
    email       $(grep '^PLATFORM_ADMIN_EMAIL=' "$ENV_FILE" | cut -d= -f2-)
    password    $(grep '^PLATFORM_ADMIN_PASSWORD=' "$ENV_FILE" | cut -d= -f2-)

  Secrets live in $INSTALL_DIR/$ENV_FILE (chmod 600). Back that file up — the
  data is unreadable without FIELD_ENCRYPTION_KEYS.

  Logs      docker compose -f deploy/docker-compose.prod.yml --env-file $ENV_FILE logs -f api
  Upgrade   re-run this script; migrations are idempotent and secrets are kept.

EOF
